version: '3'
services:
  web:
    build: .
    ports:
      - '5000:5000'
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password