name: Startgen CLI release

on:
  push:
    tags:
      - "v*.*.*" # Trigger on version tags like v0.1.0

jobs:
  release:
    name: Build and Release Homebrew Formula
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      # Install dependencies
      - name: Install Dependencies
        run: go mod tidy

      # Build binaries for all platforms
      - name: Build CLI Executable
        run: |
          mkdir -p dist
          GOOS=darwin GOARCH=amd64 go build -o dist/startgen-darwin-amd64
          GOOS=linux GOARCH=amd64 go build -o dist/startgen-linux-amd64
          GOOS=windows GOARCH=amd64 go build -o dist/startgen-windows-amd64.exe

      # Archive binaries
      - name: Archive Executables
        run: |
          cd dist
          zip startgen-darwin-amd64.zip startgen-darwin-amd64
          zip startgen-linux-amd64.zip startgen-linux-amd64
          zip startgen-windows-amd64.zip startgen-windows-amd64.exe

      # Create GitHub Release and Upload Assets
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/startgen-darwin-amd64.zip
            dist/startgen-linux-amd64.zip
            dist/startgen-windows-amd64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Generate SHA256 Checksums
      - name: Generate SHA256 Checksums
        run: |
          cd dist
          shasum -a 256 startgen-darwin-amd64 > startgen-darwin-amd64.sha256
          shasum -a 256 startgen-linux-amd64 > startgen-linux-amd64.sha256
          shasum -a 256 startgen-windows-amd64.exe > startgen-windows-amd64.sha256

      # Upload the Checksums
      - name: Upload Checksums
        uses: actions/upload-artifact@v3
        with:
          name: sha256-checksums
          path: dist/*.sha256