name: Build and Release StartGen CLI

on:
  push:
    tags:
      - "v*.*.*" # Trigger only on version tags like v1.0.0

jobs:
  build:
    name: Build and Release StartGen Executable
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # Build the executable
      - name: Build Executable
        run: |
          pyinstaller startgen.py --onefile --name startgen --exclude-module examples
          chmod +x dist/startgen

      # Rename for Windows (optional step)
      - name: Rename for OS
        run: |
          if [[ "$(uname -s)" == "Linux" ]]; then
            mv dist/startgen dist/startgen
          elif [[ "$(uname -s)" == "Darwin" ]]; then
            mv dist/startgen dist/startgen
          elif [[ "$(uname -s)" == "MINGW"* ]]; then
            mv dist/startgen dist/startgen.exe
          fi

      # Archive the executable
      - name: Archive Executable
        run: |
          mkdir -p release
          mv dist/startgen* release/
        shell: bash

      # Create GitHub Release and Upload Asset
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/startgen*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}