name: Build and Release StartGen CLI

on:
  push:
    tags:
      - "v*.*.*" # Trigger only on version tags like v1.0.0

jobs:
  build:
    name: Build and Release StartGen Executable
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # Build the executable
      - name: Build Executable
        run: |
          pyinstaller startgen.py --onefile --name startgen --exclude-module examples

      # Archive the executable
      - name: Archive Executable
        run: |
          mkdir -p release
          mv dist/startgen release/
        shell: bash

      # Create GitHub Release and Upload Asset
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/startgen
          file_globs: false
          file_name: startgen
          content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}