name: Build and Release StartGen CLI

on:
  push:
    tags:
      - "v*.*.*" # Trigger on version tags like v1.0.0

jobs:
  build:
    name: Build and Release Go CLI
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      # Cache dependencies
      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Install dependencies
      - name: Install Dependencies
        run: go mod tidy

      # Build the executable
      - name: Build CLI Executable
        run: |
          mkdir -p release
          GOOS=linux GOARCH=amd64 go build -o release/startgen-linux-amd64
          GOOS=windows GOARCH=amd64 go build -o release/startgen-windows-amd64.exe
          GOOS=darwin GOARCH=amd64 go build -o release/startgen-darwin-amd64

      # Archive the executables
      - name: Create Release Archives
        run: |
          cd release
          zip startgen-linux-amd64.zip startgen-linux-amd64
          zip startgen-windows-amd64.zip startgen-windows-amd64.exe
          zip startgen-darwin-amd64.zip startgen-darwin-amd64

      # Create GitHub Release and Upload Assets
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/startgen-linux-amd64.zip
            release/startgen-windows-amd64.zip
            release/startgen-darwin-amd64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}